In [1]:
import numpy as np
a=np.array([7,8,9,2]) # difference in output of array and list is list use , for seprate the item array not.
print(a)

[7 8 9 2]


In [3]:
import numpy as np
b=np.array([(7,9,9,2),(16,19,11,6)])
print(b)

[[ 7  9  9  2]
 [16 19 11  6]]


# Range of values in array

In [7]:
c=np.arange(10) #range of value in array
d=np.linspace(1,5,6) #set of values by interval
print(c)
print(d)

[0 1 2 3 4 5 6 7 8 9]
[1.  1.8 2.6 3.4 4.2 5. ]


# properties of array

In [13]:
a= np.array([7,9,9,2])
b= np.array([(7,9,9,2),(16,11,9,6)])
print(a.ndim )#dimensions of array
print(a.itemsize) #byte size of each element
print(a.dtype) #datatype of array
print(a.size*a.itemsize) # memory occupied- spae occupied by 1
print(a.size) # number of element in array
print(b.shape) #shape of array (rows and columns)

1
4
int32
16
4
(2, 4)


# Reshaping the array

In [16]:
b=np.array ([(7,9,9,2),(16,11,9,6)])
print(b)
b=b.reshape(4,2) #(4,3) show error so the value of rows and column should be same 
print(b)

[[ 7  9  9  2]
 [16 11  9  6]]
[[ 7  9]
 [ 9  2]
 [16 11]
 [ 9  6]]


In [21]:
b=np.array([(7,9,9,2),(16,11,9,6)])
print(b[0,2]) #slicing the element from certain row and certain column
print(b[0:,2]) # slicing element fron all rows and certain column here 0: means all rows and 2 column

9
[9 9]


In [26]:
e=np.array ([(7,9,9,2,6,11,9,6)])
print(e.min()) # return minimum value from array
print(e.max()) # return maximum value from array
print(e.sum()) # return sum of array

2
11
59


In [28]:
a=np.array([7,9,9,2])
b=np.array([(7,9,9,2),(16,11,9,6)])

print(b.sum(axis=0)) #each element of 1st dim array with same index with another dim element
print(b.sum(axis=1)) # sum of all element is 1st dim & sum of all element in 2nd dim
print(np.sqrt(a)) # squareroot of array element
print(np.std(a)) #standard deviation of array
print(np.exp(a)) #exponational of array
print(np.log(a)) #natural log-ln
print(np.log10(a)) #log based 10


[23 20 18  8]
[27 42]
[2.64575131 3.         3.         1.41421356]
2.8613807855648994
[1.09663316e+03 8.10308393e+03 8.10308393e+03 7.38905610e+00]
[1.94591015 2.19722458 2.19722458 0.69314718]
[0.84509804 0.95424251 0.95424251 0.30103   ]


In [36]:
b=np.array([(7,9,9,2),(16,11,9,6)])
f=np.array([(1,2,3,4),(5,6,7,8)])
print(np.vstack((b,f))) # vertical stack
print("--------")
print(np.hstack((b,f))) #horizontal stack
print("--------")
print(b.ravel()) #merging as single

[[ 7  9  9  2]
 [16 11  9  6]
 [ 1  2  3  4]
 [ 5  6  7  8]]
--------
[[ 7  9  9  2  1  2  3  4]
 [16 11  9  6  5  6  7  8]]
--------
[ 7  9  9  2 16 11  9  6]


# Three Dimension Array

In [38]:
threeDArray=np.array([
    [[1,2,3],[4,5,6]],
    [[-1,-2,-3],[-4,-5,-6]]
])
print(threeDArray)

[[[ 1  2  3]
  [ 4  5  6]]

 [[-1 -2 -3]
  [-4 -5 -6]]]


In [43]:
print(threeDArray[0][1][0])
print(threeDArray[0,1,0])

4
4


In [47]:
print(threeDArray.shape) #3d array
print(b.shape) #2d array 
print(a.shape) #1d array

(2, 2, 3)
(2, 4)


In [49]:
print(threeDArray.size)
print(b.size)
print(a.size)

12
8
4


In [51]:
print(threeDArray.itemsize)
print(b.itemsize)
print(a.itemsize)

4
4
4


# converting to the single dimension array 

In [57]:
for i in threeDArray.flatten(): #  to covert any dimension to single dimension it return element in verical form 
    print(i)
print("-----------------------")
print(threeDArray.ravel()) # to covert any dimension to single dimension it return element in horizontal form 

1
2
3
4
5
6
-1
-2
-3
-4
-5
-6
-----------------------
[ 1  2  3  4  5  6 -1 -2 -3 -4 -5 -6]


# Filling array with specific values

In [65]:
#zeros
zeros=np.zeros(5) # create array with zero values 
print(zeros)

[0. 0. 0. 0. 0.]


In [67]:
# ones
ones=np.ones(8) # create array with one values
print(ones)

[1. 1. 1. 1. 1. 1. 1. 1.]


In [69]:
ones=ones.astype(int) # type casting from float to int using astype
print(ones)

[1 1 1 1 1 1 1 1]


In [71]:
# ranfe
ranges=np.arange(5.6,9.8)
print(ranges)

[5.6 6.6 7.6 8.6 9.6]


In [73]:
#linspace
linspace=np.linspace(3,6,10)
print(linspace)

[3.         3.33333333 3.66666667 4.         4.33333333 4.66666667
 5.         5.33333333 5.66666667 6.        ]


In [ ]:
#help(linspace)

# scalar operation

In [75]:
matrix=np.array([[76,34,89],[23,34,45]])
print(matrix)

[[76 34 89]
 [23 34 45]]


In [77]:
print(matrix + 2) # add  2 

[[78 36 91]
 [25 36 47]]


In [80]:
python=[[76,34,89],[23,34,45]]
print(python*2) # it simply copying

[[76, 34, 89], [23, 34, 45], [76, 34, 89], [23, 34, 45]]


In [92]:
print(matrix.T)

[[76 23]
 [34 34]
 [89 45]]


In [86]:
print(matrix[1,]) # return first ro

[23 34 45]


In [90]:
print("1-dimension")
full=np.full(10,5)
print(full)

print("2-dimension")
full=np.full((2,2),10)
print(full)

print("3-dimension")
full=np.full((2,5,4),5)
print(full)


1-dimension
[5 5 5 5 5 5 5 5 5 5]
2-dimension
[[10 10]
 [10 10]]
3-dimension
[[[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]

 [[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]]


# element-wise operation

In [94]:
python1=[[76,34,89],[23,34,45]] # it will simply create new list and copy all values in it for this number of values should be same 
python2=[[76,34,89],[23,34,45]]
python1 + python2

[[76, 34, 89], [23, 34, 45], [76, 34, 89], [23, 34, 45]]

In [97]:
matrix1=np.array([[1,2,3],[4,5,6],[13,14,15]]) #n*m  no of column and no of rows should be same
matrix2=np.array([[7,8,9],[10,11,12],[16,17,18]])
print(np.matmul(matrix1,matrix2))

[[ 75  81  87]
 [174 189 204]
 [471 513 555]]


In [104]:
print(matrix1 + matrix2)

[[ 8 10 12]
 [14 16 18]
 [29 31 33]]


In [110]:
print(matrix1 * matrix2)

[[  7  16  27]
 [ 40  55  72]
 [208 238 270]]


In [106]:
print(matrix1 - matrix2)

[[-6 -6 -6]
 [-6 -6 -6]
 [-3 -3 -3]]


# statical function in numpy labrary

In [101]:
marks= np.array([
    [87,90,89],[100,87,90],
    [94,77,90],[100,86,98]
])

In [118]:
print(marks.min())
print(marks.max())
print(marks.sum())
print(marks.mean())
print(marks.std())
print(marks.var(),2)


77
100
1088
90.66666666666667
6.315765107165473
39.88888888888889 2


In [116]:
print(marks.min(axis=1)) # axis 1 means rowwise 
print(marks.max(axis=1)) # axis 0 means columnwise
print(marks.sum(axis=1))
print(marks.mean(axis=1))
print(marks.std(axis=1))

[87 87 77 86]
[ 90 100  94 100]
[266 277 261 284]
[88.66666667 92.33333333 87.         94.66666667]
[1.24721913 5.55777733 7.25718035 6.18241233]


In [122]:
 # append
x=np.array([0,1,2,3,4,])
y=np.array([6,7,8,9,10])
z=np.array([11,12,13,14,15])

np.append(x,(2,3)) # return a new array dont append in the existing array

array([0, 1, 2, 3, 4, 2, 3])

In [124]:
np.hstack([x,y,z])

array([ 0,  1,  2,  3,  4,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [126]:
np.vstack([x,y,z])


array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [130]:
new_array=np.array([1,2,3])
x=np.append([[1,2,3],[4,5,6]],[[1,2,3],new_array],axis=0)
print(x)

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [1 2 3]]


In [132]:
np.transpose(x) #x.T PERFORM THE SAME OPERATION

array([[1, 4, 1, 1],
       [2, 5, 2, 2],
       [3, 6, 3, 3]])

In [ ]:
# boolean indixing

In [136]:
arr=np.arange(7)
print(arr)

[0 1 2 3 4 5 6]


In [138]:
arr>4

array([False, False, False, False, False,  True,  True])

In [140]:
arr[arr>4]

array([5, 6])

# reshaping 

In [142]:
array=np.arange(12)

In [144]:
array.shape=(3,4)

In [146]:
np.arange(12).reshape((2,3,2))

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

# generating random value

In [150]:
np.random.randint(5)

4

In [148]:
np.random.randint(10,20,(5,5))

array([[18, 19, 10, 15, 12],
       [11, 15, 11, 16, 15],
       [15, 19, 18, 13, 18],
       [19, 18, 15, 10, 18],
       [17, 10, 19, 14, 12]])

In [169]:
letters=list("aeiou")
np.random.choice(letters,13)

array(['u', 'e', 'e', 'a', 'u', 'o', 'a', 'a', 'i', 'e', 'e', 'u', 'i'],
      dtype='<U1')

In [159]:
np.random.choice(letters,5,replace=False)

array(['a', 'n', 'h', 'r', 'a'], dtype='<U1')

In [171]:
np.random.choice(letters,15,p=[0.4,0.3,0.1,0.1,0.1])

array(['e', 'a', 'u', 'e', 'a', 'e', 'u', 'e', 'e', 'i', 'a', 'o', 'a',
       'a', 'a'], dtype='<U1')

# save and load value

In [165]:
array=np.random.randint(10,20,(5,5))
np.save("array_file",array)

In [167]:
array2=np.load("array_file.npy")
print(array2)

[[19 18 10 16 13]
 [19 10 19 12 16]
 [17 19 11 11 14]
 [12 12 13 18 17]
 [12 16 17 10 10]]
